package com.shoe.entities;
// Generated Dec 3, 2018 9:08:44 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "quanlygiay", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Roles implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);

	public Roles() {
	}

	public Roles(String name) {
		this.name = name;
	}

	public Roles(String name, Set<UserRoles> userRoleses) {
		this.name = name;
		this.userRoleses = userRoleses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

}
