package com.shoe.entities;
// Generated Dec 3, 2018 9:08:44 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "quanlygiay", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "username") })
public class Users implements java.io.Serializable {

	private Integer userId;
	private String email;
	private String username;
	private String password;
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);
	private Set<KhachHang> khachHangs = new HashSet<KhachHang>(0);

	public Users() {
	}

	public Users(String password) {
		this.password = password;
	}

	public Users(String email, String username, String password, Set<UserRoles> userRoleses,
			Set<KhachHang> khachHangs) {
		this.email = email;
		this.username = username;
		this.password = password;
		this.userRoleses = userRoleses;
		this.khachHangs = khachHangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "email", unique = true, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", unique = true, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 256)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<KhachHang> getKhachHangs() {
		return this.khachHangs;
	}

	public void setKhachHangs(Set<KhachHang> khachHangs) {
		this.khachHangs = khachHangs;
	}

}
