package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

/**
 * ChiTietPhieuNhap generated by hbm2java
 */
public class ChiTietPhieuNhap implements java.io.Serializable {

	private Integer idChiTietPhieuNhap;
	private ChiTietGiay chiTietGiay;
	private PhieuNhap phieuNhap;
	private int soLuong;
	private Integer giaVon;

	public ChiTietPhieuNhap() {
	}

	public ChiTietPhieuNhap(ChiTietGiay chiTietGiay, PhieuNhap phieuNhap, int soLuong) {
		this.chiTietGiay = chiTietGiay;
		this.phieuNhap = phieuNhap;
		this.soLuong = soLuong;
	}

	public ChiTietPhieuNhap(ChiTietGiay chiTietGiay, PhieuNhap phieuNhap, int soLuong, Integer giaVon) {
		this.chiTietGiay = chiTietGiay;
		this.phieuNhap = phieuNhap;
		this.soLuong = soLuong;
		this.giaVon = giaVon;
	}

	public Integer getIdChiTietPhieuNhap() {
		return this.idChiTietPhieuNhap;
	}

	public void setIdChiTietPhieuNhap(Integer idChiTietPhieuNhap) {
		this.idChiTietPhieuNhap = idChiTietPhieuNhap;
	}

	public ChiTietGiay getChiTietGiay() {
		return this.chiTietGiay;
	}

	public void setChiTietGiay(ChiTietGiay chiTietGiay) {
		this.chiTietGiay = chiTietGiay;
	}

	public PhieuNhap getPhieuNhap() {
		return this.phieuNhap;
	}

	public void setPhieuNhap(PhieuNhap phieuNhap) {
		this.phieuNhap = phieuNhap;
	}

	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	public Integer getGiaVon() {
		return this.giaVon;
	}

	public void setGiaVon(Integer giaVon) {
		this.giaVon = giaVon;
	}

}
