package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ChiTietGiay generated by hbm2java
 */
public class ChiTietGiay implements java.io.Serializable {

	private Integer idChiTietGiay;
	private Giay giay;
	private int size;
	private int soLuong;
	private Boolean xoaFlag;
	private Set chiTietPhieuNhaps = new HashSet(0);
	private Set chiTietDonHangs = new HashSet(0);

	public ChiTietGiay() {
	}

	public ChiTietGiay(Giay giay, int size, int soLuong) {
		this.giay = giay;
		this.size = size;
		this.soLuong = soLuong;
	}

	public ChiTietGiay(Giay giay, int size, int soLuong, Boolean xoaFlag, Set chiTietPhieuNhaps, Set chiTietDonHangs) {
		this.giay = giay;
		this.size = size;
		this.soLuong = soLuong;
		this.xoaFlag = xoaFlag;
		this.chiTietPhieuNhaps = chiTietPhieuNhaps;
		this.chiTietDonHangs = chiTietDonHangs;
	}

	public Integer getIdChiTietGiay() {
		return this.idChiTietGiay;
	}

	public void setIdChiTietGiay(Integer idChiTietGiay) {
		this.idChiTietGiay = idChiTietGiay;
	}

	public Giay getGiay() {
		return this.giay;
	}

	public void setGiay(Giay giay) {
		this.giay = giay;
	}

	public int getSize() {
		return this.size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	public Boolean getXoaFlag() {
		return this.xoaFlag;
	}

	public void setXoaFlag(Boolean xoaFlag) {
		this.xoaFlag = xoaFlag;
	}

	public Set getChiTietPhieuNhaps() {
		return this.chiTietPhieuNhaps;
	}

	public void setChiTietPhieuNhaps(Set chiTietPhieuNhaps) {
		this.chiTietPhieuNhaps = chiTietPhieuNhaps;
	}

	public Set getChiTietDonHangs() {
		return this.chiTietDonHangs;
	}

	public void setChiTietDonHangs(Set chiTietDonHangs) {
		this.chiTietDonHangs = chiTietDonHangs;
	}

}
