package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

/**
 * ChiTietDonHang generated by hbm2java
 */
public class ChiTietDonHang implements java.io.Serializable {

	private Integer idChiTietDonHang;
	private ChiTietGiay chiTietGiay;
	private DonHang donHang;
	private int soLuong;
	private int thanhTien;

	public ChiTietDonHang() {
	}

	public ChiTietDonHang(ChiTietGiay chiTietGiay, DonHang donHang, int soLuong, int thanhTien) {
		this.chiTietGiay = chiTietGiay;
		this.donHang = donHang;
		this.soLuong = soLuong;
		this.thanhTien = thanhTien;
	}

	public Integer getIdChiTietDonHang() {
		return this.idChiTietDonHang;
	}

	public void setIdChiTietDonHang(Integer idChiTietDonHang) {
		this.idChiTietDonHang = idChiTietDonHang;
	}

	public ChiTietGiay getChiTietGiay() {
		return this.chiTietGiay;
	}

	public void setChiTietGiay(ChiTietGiay chiTietGiay) {
		this.chiTietGiay = chiTietGiay;
	}

	public DonHang getDonHang() {
		return this.donHang;
	}

	public void setDonHang(DonHang donHang) {
		this.donHang = donHang;
	}

	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	public int getThanhTien() {
		return this.thanhTien;
	}

	public void setThanhTien(int thanhTien) {
		this.thanhTien = thanhTien;
	}

}
