package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Giay generated by hbm2java
 */
public class Giay implements java.io.Serializable {

	private Integer idGiay;
	private GioiTinh gioiTinh;
	private LoaiGiay loaiGiay;
	private String maGiay;
	private String tenGiay;
	private int giaBan;
	private String ghiChu;
	private String img1;
	private String img2;
	private String img3;
	private String img4;
	private Integer soLuongBan;
	private Boolean xoaFlag;
	private Set chiTietGiays = new HashSet(0);

	public Giay() {
	}

	public Giay(GioiTinh gioiTinh, LoaiGiay loaiGiay, String maGiay, String tenGiay, int giaBan) {
		this.gioiTinh = gioiTinh;
		this.loaiGiay = loaiGiay;
		this.maGiay = maGiay;
		this.tenGiay = tenGiay;
		this.giaBan = giaBan;
	}

	public Giay(GioiTinh gioiTinh, LoaiGiay loaiGiay, String maGiay, String tenGiay, int giaBan, String ghiChu,
			String img1, String img2, String img3, String img4, Integer soLuongBan, Boolean xoaFlag, Set chiTietGiays) {
		this.gioiTinh = gioiTinh;
		this.loaiGiay = loaiGiay;
		this.maGiay = maGiay;
		this.tenGiay = tenGiay;
		this.giaBan = giaBan;
		this.ghiChu = ghiChu;
		this.img1 = img1;
		this.img2 = img2;
		this.img3 = img3;
		this.img4 = img4;
		this.soLuongBan = soLuongBan;
		this.xoaFlag = xoaFlag;
		this.chiTietGiays = chiTietGiays;
	}

	public Integer getIdGiay() {
		return this.idGiay;
	}

	public void setIdGiay(Integer idGiay) {
		this.idGiay = idGiay;
	}

	public GioiTinh getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(GioiTinh gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	public LoaiGiay getLoaiGiay() {
		return this.loaiGiay;
	}

	public void setLoaiGiay(LoaiGiay loaiGiay) {
		this.loaiGiay = loaiGiay;
	}

	public String getMaGiay() {
		return this.maGiay;
	}

	public void setMaGiay(String maGiay) {
		this.maGiay = maGiay;
	}

	public String getTenGiay() {
		return this.tenGiay;
	}

	public void setTenGiay(String tenGiay) {
		this.tenGiay = tenGiay;
	}

	public int getGiaBan() {
		return this.giaBan;
	}

	public void setGiaBan(int giaBan) {
		this.giaBan = giaBan;
	}

	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	public String getImg1() {
		return this.img1;
	}

	public void setImg1(String img1) {
		this.img1 = img1;
	}

	public String getImg2() {
		return this.img2;
	}

	public void setImg2(String img2) {
		this.img2 = img2;
	}

	public String getImg3() {
		return this.img3;
	}

	public void setImg3(String img3) {
		this.img3 = img3;
	}

	public String getImg4() {
		return this.img4;
	}

	public void setImg4(String img4) {
		this.img4 = img4;
	}

	public Integer getSoLuongBan() {
		return this.soLuongBan;
	}

	public void setSoLuongBan(Integer soLuongBan) {
		this.soLuongBan = soLuongBan;
	}

	public Boolean getXoaFlag() {
		return this.xoaFlag;
	}

	public void setXoaFlag(Boolean xoaFlag) {
		this.xoaFlag = xoaFlag;
	}

	public Set getChiTietGiays() {
		return this.chiTietGiays;
	}

	public void setChiTietGiays(Set chiTietGiays) {
		this.chiTietGiays = chiTietGiays;
	}

}
