package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * GioiTinh generated by hbm2java
 */
public class GioiTinh implements java.io.Serializable {

	private int idGioiTinh;
	private String tenGioiTinh;
	private Set giays = new HashSet(0);

	public GioiTinh() {
	}

	public GioiTinh(int idGioiTinh, String tenGioiTinh) {
		this.idGioiTinh = idGioiTinh;
		this.tenGioiTinh = tenGioiTinh;
	}

	public GioiTinh(int idGioiTinh, String tenGioiTinh, Set giays) {
		this.idGioiTinh = idGioiTinh;
		this.tenGioiTinh = tenGioiTinh;
		this.giays = giays;
	}

	public int getIdGioiTinh() {
		return this.idGioiTinh;
	}

	public void setIdGioiTinh(int idGioiTinh) {
		this.idGioiTinh = idGioiTinh;
	}

	public String getTenGioiTinh() {
		return this.tenGioiTinh;
	}

	public void setTenGioiTinh(String tenGioiTinh) {
		this.tenGioiTinh = tenGioiTinh;
	}

	public Set getGiays() {
		return this.giays;
	}

	public void setGiays(Set giays) {
		this.giays = giays;
	}

}
