package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * HangSanXuat generated by hbm2java
 */
public class HangSanXuat implements java.io.Serializable {

	private Integer idHangSanXuat;
	private String tenHangSanXuat;
	private Boolean xoaFlag;
	private Set loaiGiays = new HashSet(0);
	private Set phieuNhaps = new HashSet(0);

	public HangSanXuat() {
	}

	public HangSanXuat(String tenHangSanXuat, Boolean xoaFlag, Set loaiGiays, Set phieuNhaps) {
		this.tenHangSanXuat = tenHangSanXuat;
		this.xoaFlag = xoaFlag;
		this.loaiGiays = loaiGiays;
		this.phieuNhaps = phieuNhaps;
	}

	public Integer getIdHangSanXuat() {
		return this.idHangSanXuat;
	}

	public void setIdHangSanXuat(Integer idHangSanXuat) {
		this.idHangSanXuat = idHangSanXuat;
	}

	public String getTenHangSanXuat() {
		return this.tenHangSanXuat;
	}

	public void setTenHangSanXuat(String tenHangSanXuat) {
		this.tenHangSanXuat = tenHangSanXuat;
	}

	public Boolean getXoaFlag() {
		return this.xoaFlag;
	}

	public void setXoaFlag(Boolean xoaFlag) {
		this.xoaFlag = xoaFlag;
	}

	public Set getLoaiGiays() {
		return this.loaiGiays;
	}

	public void setLoaiGiays(Set loaiGiays) {
		this.loaiGiays = loaiGiays;
	}

	public Set getPhieuNhaps() {
		return this.phieuNhaps;
	}

	public void setPhieuNhaps(Set phieuNhaps) {
		this.phieuNhaps = phieuNhaps;
	}

}
