package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * KhachHang generated by hbm2java
 */
public class KhachHang implements java.io.Serializable {

	private Integer idKhachHang;
	private Users users;
	private String tenKhachHang;
	private String diaChi;
	private int soDienThoai;
	private Set donHangs = new HashSet(0);

	public KhachHang() {
	}

	public KhachHang(String tenKhachHang, String diaChi, int soDienThoai) {
		this.tenKhachHang = tenKhachHang;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
	}

	public KhachHang(Users users, String tenKhachHang, String diaChi, int soDienThoai, Set donHangs) {
		this.users = users;
		this.tenKhachHang = tenKhachHang;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
		this.donHangs = donHangs;
	}

	public Integer getIdKhachHang() {
		return this.idKhachHang;
	}

	public void setIdKhachHang(Integer idKhachHang) {
		this.idKhachHang = idKhachHang;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getTenKhachHang() {
		return this.tenKhachHang;
	}

	public void setTenKhachHang(String tenKhachHang) {
		this.tenKhachHang = tenKhachHang;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public int getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(int soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	public Set getDonHangs() {
		return this.donHangs;
	}

	public void setDonHangs(Set donHangs) {
		this.donHangs = donHangs;
	}

}
