package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * LoaiGiay generated by hbm2java
 */
public class LoaiGiay implements java.io.Serializable {

	private Integer idLoaiGiay;
	private HangSanXuat hangSanXuat;
	private String tenLoaiGiay;
	private Boolean xoaFlag;
	private Set giays = new HashSet(0);

	public LoaiGiay() {
	}

	public LoaiGiay(HangSanXuat hangSanXuat, String tenLoaiGiay) {
		this.hangSanXuat = hangSanXuat;
		this.tenLoaiGiay = tenLoaiGiay;
	}

	public LoaiGiay(HangSanXuat hangSanXuat, String tenLoaiGiay, Boolean xoaFlag, Set giays) {
		this.hangSanXuat = hangSanXuat;
		this.tenLoaiGiay = tenLoaiGiay;
		this.xoaFlag = xoaFlag;
		this.giays = giays;
	}

	public Integer getIdLoaiGiay() {
		return this.idLoaiGiay;
	}

	public void setIdLoaiGiay(Integer idLoaiGiay) {
		this.idLoaiGiay = idLoaiGiay;
	}

	public HangSanXuat getHangSanXuat() {
		return this.hangSanXuat;
	}

	public void setHangSanXuat(HangSanXuat hangSanXuat) {
		this.hangSanXuat = hangSanXuat;
	}

	public String getTenLoaiGiay() {
		return this.tenLoaiGiay;
	}

	public void setTenLoaiGiay(String tenLoaiGiay) {
		this.tenLoaiGiay = tenLoaiGiay;
	}

	public Boolean getXoaFlag() {
		return this.xoaFlag;
	}

	public void setXoaFlag(Boolean xoaFlag) {
		this.xoaFlag = xoaFlag;
	}

	public Set getGiays() {
		return this.giays;
	}

	public void setGiays(Set giays) {
		this.giays = giays;
	}

}
