package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PhieuNhap generated by hbm2java
 */
public class PhieuNhap implements java.io.Serializable {

	private Integer idPhieuNhap;
	private HangSanXuat hangSanXuat;
	private Date ngayNhap;
	private int tongSoLuong;
	private Set chiTietPhieuNhaps = new HashSet(0);

	public PhieuNhap() {
	}

	public PhieuNhap(HangSanXuat hangSanXuat, Date ngayNhap, int tongSoLuong) {
		this.hangSanXuat = hangSanXuat;
		this.ngayNhap = ngayNhap;
		this.tongSoLuong = tongSoLuong;
	}

	public PhieuNhap(HangSanXuat hangSanXuat, Date ngayNhap, int tongSoLuong, Set chiTietPhieuNhaps) {
		this.hangSanXuat = hangSanXuat;
		this.ngayNhap = ngayNhap;
		this.tongSoLuong = tongSoLuong;
		this.chiTietPhieuNhaps = chiTietPhieuNhaps;
	}

	public Integer getIdPhieuNhap() {
		return this.idPhieuNhap;
	}

	public void setIdPhieuNhap(Integer idPhieuNhap) {
		this.idPhieuNhap = idPhieuNhap;
	}

	public HangSanXuat getHangSanXuat() {
		return this.hangSanXuat;
	}

	public void setHangSanXuat(HangSanXuat hangSanXuat) {
		this.hangSanXuat = hangSanXuat;
	}

	public Date getNgayNhap() {
		return this.ngayNhap;
	}

	public void setNgayNhap(Date ngayNhap) {
		this.ngayNhap = ngayNhap;
	}

	public int getTongSoLuong() {
		return this.tongSoLuong;
	}

	public void setTongSoLuong(int tongSoLuong) {
		this.tongSoLuong = tongSoLuong;
	}

	public Set getChiTietPhieuNhaps() {
		return this.chiTietPhieuNhaps;
	}

	public void setChiTietPhieuNhaps(Set chiTietPhieuNhaps) {
		this.chiTietPhieuNhaps = chiTietPhieuNhaps;
	}

}
