package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TinhTrangDonHang generated by hbm2java
 */
public class TinhTrangDonHang implements java.io.Serializable {

	private Integer idTinhTrang;
	private String tenTinhTrang;
	private Set donHangs = new HashSet(0);

	public TinhTrangDonHang() {
	}

	public TinhTrangDonHang(String tenTinhTrang, Set donHangs) {
		this.tenTinhTrang = tenTinhTrang;
		this.donHangs = donHangs;
	}

	public Integer getIdTinhTrang() {
		return this.idTinhTrang;
	}

	public void setIdTinhTrang(Integer idTinhTrang) {
		this.idTinhTrang = idTinhTrang;
	}

	public String getTenTinhTrang() {
		return this.tenTinhTrang;
	}

	public void setTenTinhTrang(String tenTinhTrang) {
		this.tenTinhTrang = tenTinhTrang;
	}

	public Set getDonHangs() {
		return this.donHangs;
	}

	public void setDonHangs(Set donHangs) {
		this.donHangs = donHangs;
	}

}
