package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer idUser;
	private String email;
	private String username;
	private String password;
	private Set khachHangs = new HashSet(0);

	public Users() {
	}

	public Users(String password) {
		this.password = password;
	}

	public Users(String email, String username, String password, Set khachHangs) {
		this.email = email;
		this.username = username;
		this.password = password;
		this.khachHangs = khachHangs;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getKhachHangs() {
		return this.khachHangs;
	}

	public void setKhachHangs(Set khachHangs) {
		this.khachHangs = khachHangs;
	}

}
