package com.shoe.test;
// Generated Dec 3, 2018 6:37:20 PM by Hibernate Tools 5.3.6.Final

/**
 * UserRoles generated by hbm2java
 */
public class UserRoles implements java.io.Serializable {

	private UserRolesId id;

	public UserRoles() {
	}

	public UserRoles(UserRolesId id) {
		this.id = id;
	}

	public UserRolesId getId() {
		return this.id;
	}

	public void setId(UserRolesId id) {
		this.id = id;
	}

}
