package uit.entity;
// Generated Dec 2, 2018 12:39:47 AM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DonHang generated by hbm2java
 */
@Entity
@Table(name = "don_hang", catalog = "quanlygiay")
public class DonHang implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4214968658888521722L;
	private Integer idDonHang;
	private KhachHang khachHang;
	private TinhTrangDonHang tinhTrangDonHang;
	private Date ngayDat;
	private Date ngayGiao;
	private int tongTien;
	private Set<ChiTietDonHang> chiTietDonHangs = new HashSet<ChiTietDonHang>(0);

	public DonHang() {
	}

	public DonHang(KhachHang khachHang, TinhTrangDonHang tinhTrangDonHang, Date ngayDat, Date ngayGiao, int tongTien) {
		this.khachHang = khachHang;
		this.tinhTrangDonHang = tinhTrangDonHang;
		this.ngayDat = ngayDat;
		this.ngayGiao = ngayGiao;
		this.tongTien = tongTien;
	}

	public DonHang(KhachHang khachHang, TinhTrangDonHang tinhTrangDonHang, Date ngayDat, Date ngayGiao, int tongTien,
			Set<ChiTietDonHang> chiTietDonHangs) {
		this.khachHang = khachHang;
		this.tinhTrangDonHang = tinhTrangDonHang;
		this.ngayDat = ngayDat;
		this.ngayGiao = ngayGiao;
		this.tongTien = tongTien;
		this.chiTietDonHangs = chiTietDonHangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_don_hang", unique = true, nullable = false)
	public Integer getIdDonHang() {
		return this.idDonHang;
	}

	public void setIdDonHang(Integer idDonHang) {
		this.idDonHang = idDonHang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_khach_hang", nullable = false)
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tinh_trang", nullable = false)
	public TinhTrangDonHang getTinhTrangDonHang() {
		return this.tinhTrangDonHang;
	}

	public void setTinhTrangDonHang(TinhTrangDonHang tinhTrangDonHang) {
		this.tinhTrangDonHang = tinhTrangDonHang;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay_dat", nullable = false, length = 19)
	public Date getNgayDat() {
		return this.ngayDat;
	}

	public void setNgayDat(Date ngayDat) {
		this.ngayDat = ngayDat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay_giao", nullable = false, length = 19)
	public Date getNgayGiao() {
		return this.ngayGiao;
	}

	public void setNgayGiao(Date ngayGiao) {
		this.ngayGiao = ngayGiao;
	}

	@Column(name = "tong_tien", nullable = false)
	public int getTongTien() {
		return this.tongTien;
	}

	public void setTongTien(int tongTien) {
		this.tongTien = tongTien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donHang")
	public Set<ChiTietDonHang> getChiTietDonHangs() {
		return this.chiTietDonHangs;
	}

	public void setChiTietDonHangs(Set<ChiTietDonHang> chiTietDonHangs) {
		this.chiTietDonHangs = chiTietDonHangs;
	}

}
