package uit.entity;
// Generated Dec 2, 2018 9:33:48 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiGiay generated by hbm2java
 */
@Entity
@Table(name = "loai_giay", catalog = "quanlygiay")
public class LoaiGiay implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1374703052976038832L;

	private Integer idLoaiGiay;
	private HangSanXuat hangSanXuat;
	private String tenLoaiGiay;
	private Boolean xoaFlag;
	private Set<Giay> giays = new HashSet<Giay>(0);

	public LoaiGiay() {
	}

	public LoaiGiay(HangSanXuat hangSanXuat, String tenLoaiGiay) {
		this.hangSanXuat = hangSanXuat;
		this.tenLoaiGiay = tenLoaiGiay;
	}

	public LoaiGiay(HangSanXuat hangSanXuat, String tenLoaiGiay, Boolean xoaFlag, Set<Giay> giays) {
		this.hangSanXuat = hangSanXuat;
		this.tenLoaiGiay = tenLoaiGiay;
		this.xoaFlag = xoaFlag;
		this.giays = giays;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_loai_giay", unique = true, nullable = false)
	public Integer getIdLoaiGiay() {
		return this.idLoaiGiay;
	}

	public void setIdLoaiGiay(Integer idLoaiGiay) {
		this.idLoaiGiay = idLoaiGiay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hang_san_xuat", nullable = false)
	public HangSanXuat getHangSanXuat() {
		return this.hangSanXuat;
	}

	public void setHangSanXuat(HangSanXuat hangSanXuat) {
		this.hangSanXuat = hangSanXuat;
	}

	@Column(name = "ten_loai_giay", nullable = false, length = 100)
	public String getTenLoaiGiay() {
		return this.tenLoaiGiay;
	}

	public void setTenLoaiGiay(String tenLoaiGiay) {
		this.tenLoaiGiay = tenLoaiGiay;
	}

	@Column(name = "xoa_flag")
	public Boolean getXoaFlag() {
		return this.xoaFlag;
	}

	public void setXoaFlag(Boolean xoaFlag) {
		this.xoaFlag = xoaFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiGiay")
	public Set<Giay> getGiays() {
		return this.giays;
	}

	public void setGiays(Set<Giay> giays) {
		this.giays = giays;
	}

}
