package com.shoe.entities;
// Generated Nov 27, 2018 12:36:27 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChiTietGiay generated by hbm2java
 */
@Entity
@Table(name = "chi_tiet_giay", catalog = "quanlygiay")
public class ChiTietGiay implements java.io.Serializable {

	private Integer idChiTietGiay;
	private Giay giay;
	private int size;
	private int soLuong;
	private Boolean xoaFlag;
	private Set<ChiTietPhieuNhap> chiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>(0);
	private Set<ChiTietDonHang> chiTietDonHangs = new HashSet<ChiTietDonHang>(0);

	public ChiTietGiay() {
	}

	public ChiTietGiay(Giay giay, int size, int soLuong) {
		this.giay = giay;
		this.size = size;
		this.soLuong = soLuong;
	}

	public ChiTietGiay(Giay giay, int size, int soLuong, Boolean xoaFlag, Set<ChiTietPhieuNhap> chiTietPhieuNhaps,
			Set<ChiTietDonHang> chiTietDonHangs) {
		this.giay = giay;
		this.size = size;
		this.soLuong = soLuong;
		this.xoaFlag = xoaFlag;
		this.chiTietPhieuNhaps = chiTietPhieuNhaps;
		this.chiTietDonHangs = chiTietDonHangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_chi_tiet_giay", unique = true, nullable = false)
	public Integer getIdChiTietGiay() {
		return this.idChiTietGiay;
	}

	public void setIdChiTietGiay(Integer idChiTietGiay) {
		this.idChiTietGiay = idChiTietGiay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giay", nullable = false)
	public Giay getGiay() {
		return this.giay;
	}

	public void setGiay(Giay giay) {
		this.giay = giay;
	}

	@Column(name = "size", nullable = false)
	public int getSize() {
		return this.size;
	}

	public void setSize(int size) {
		this.size = size;
	}

	@Column(name = "so_luong", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "xoa_flag")
	public Boolean getXoaFlag() {
		return this.xoaFlag;
	}

	public void setXoaFlag(Boolean xoaFlag) {
		this.xoaFlag = xoaFlag;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chiTietGiay")
	public Set<ChiTietPhieuNhap> getChiTietPhieuNhaps() {
		return this.chiTietPhieuNhaps;
	}

	public void setChiTietPhieuNhaps(Set<ChiTietPhieuNhap> chiTietPhieuNhaps) {
		this.chiTietPhieuNhaps = chiTietPhieuNhaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chiTietGiay")
	public Set<ChiTietDonHang> getChiTietDonHangs() {
		return this.chiTietDonHangs;
	}

	public void setChiTietDonHangs(Set<ChiTietDonHang> chiTietDonHangs) {
		this.chiTietDonHangs = chiTietDonHangs;
	}

}
