package com.shoe.entities;
// Generated Oct 28, 2018 6:49:43 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Giay generated by hbm2java
 */
@Entity
@Table(name = "giay", catalog = "quanlygiay", uniqueConstraints = { @UniqueConstraint(columnNames = "ma_giay"),
		@UniqueConstraint(columnNames = "ten_giay") })
public class Giay implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -30872812781481697L;
	private int idGiay;
	private GioiTinh gioiTinh;
	private LoaiGiay loaiGiay;
	private String maGiay;
	private String tenGiay;
	private int soLuongBan;
	private long giaBan;
	private String ghiChu;
	private String img1;
	private String img2;
	private String img3;
	private String img4;
	private Date deleteYmd;
	private Set<ChiTietGiay> chiTietGiays = new HashSet<ChiTietGiay>(0);

	public Giay() {
	}

	public Giay(int idGiay, LoaiGiay loaiGiay, String maGiay, String tenGiay, int soLuongBan, long giaBan) {
		this.idGiay = idGiay;
		this.loaiGiay = loaiGiay;
		this.maGiay = maGiay;
		this.tenGiay = tenGiay;
		this.soLuongBan = soLuongBan;
		this.giaBan = giaBan;
	}

	public Giay(int idGiay, GioiTinh gioiTinh, LoaiGiay loaiGiay, String maGiay, String tenGiay, int soLuongBan,
	long giaBan, String ghiChu, String img1, String img2, String img3, String img4, Date deleteYmd,
			Set<ChiTietGiay> chiTietGiays) {
		this.idGiay = idGiay;
		this.gioiTinh = gioiTinh;
		this.loaiGiay = loaiGiay;
		this.maGiay = maGiay;
		this.tenGiay = tenGiay;
		this.soLuongBan = soLuongBan;
		this.giaBan = giaBan;
		this.ghiChu = ghiChu;
		this.img1 = img1;
		this.img2 = img2;
		this.img3 = img3;
		this.img4 = img4;
		this.deleteYmd = deleteYmd;
		this.chiTietGiays = chiTietGiays;
	}

	@Id
	@Column(name = "id_giay", unique = true, nullable = false)
	public int getIdGiay() {
		return this.idGiay;
	}

	public void setIdGiay(int idGiay) {
		this.idGiay = idGiay;
	}

	@ManyToOne
	@JoinColumn(name = "id_gioi_tinh")
	public GioiTinh getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(GioiTinh gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@ManyToOne
	@JoinColumn(name = "id_loai_giay", nullable = false)
	public LoaiGiay getLoaiGiay() {
		return this.loaiGiay;
	}

	public void setLoaiGiay(LoaiGiay loaiGiay) {
		this.loaiGiay = loaiGiay;
	}

	@Column(name = "ma_giay", unique = true, nullable = false, length = 50)
	public String getMaGiay() {
		return this.maGiay;
	}

	public void setMaGiay(String maGiay) {
		this.maGiay = maGiay;
	}

	@Column(name = "ten_giay", unique = true, nullable = false, length = 50)
	public String getTenGiay() {
		return this.tenGiay;
	}

	public void setTenGiay(String tenGiay) {
		this.tenGiay = tenGiay;
	}

	@Column(name = "so_luong_ban", nullable = false)
	public int getSoLuongBan() {
		return this.soLuongBan;
	}

	public void setSoLuongBan(int soLuongBan) {
		this.soLuongBan = soLuongBan;
	}

	@Column(name = "gia_ban", nullable = false, length = 16777215)
	public long getGiaBan() {
		return this.giaBan;
	}

	public void setGiaBan(long giaBan) {
		this.giaBan = giaBan;
	}

	@Column(name = "ghi_chu", length = 65535)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	@Column(name = "img1", length = 65535)
	public String getImg1() {
		return this.img1;
	}

	public void setImg1(String img1) {
		this.img1 = img1;
	}

	@Column(name = "img2", length = 65535)
	public String getImg2() {
		return this.img2;
	}

	public void setImg2(String img2) {
		this.img2 = img2;
	}

	@Column(name = "img3", length = 65535)
	public String getImg3() {
		return this.img3;
	}

	public void setImg3(String img3) {
		this.img3 = img3;
	}

	@Column(name = "img4", length = 65535)
	public String getImg4() {
		return this.img4;
	}

	public void setImg4(String img4) {
		this.img4 = img4;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delete_ymd", length = 26)
	public Date getDeleteYmd() {
		return this.deleteYmd;
	}

	public void setDeleteYmd(Date deleteYmd) {
		this.deleteYmd = deleteYmd;
	}

	@OneToMany(mappedBy = "giay")
	public Set<ChiTietGiay> getChiTietGiays() {
		return this.chiTietGiays;
	}

	public void setChiTietGiays(Set<ChiTietGiay> chiTietGiays) {
		this.chiTietGiays = chiTietGiays;
	}

}
