package com.shoe.entities;
// Generated Oct 28, 2018 6:49:43 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * HangSanXuat generated by hbm2java
 */
@Entity
@Table(name = "hang_san_xuat", catalog = "quanlygiay")
public class HangSanXuat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6006291318002629385L;
	private int idHangSanXuat;
	private String tenHangSanXuat;
	private Set<LoaiGiay> loaiGiays = new HashSet<LoaiGiay>(0);

	public HangSanXuat() {
	}

	public HangSanXuat(int idHangSanXuat) {
		this.idHangSanXuat = idHangSanXuat;
	}

	public HangSanXuat(int idHangSanXuat, String tenHangSanXuat, Set<LoaiGiay> loaiGiays) {
		this.idHangSanXuat = idHangSanXuat;
		this.tenHangSanXuat = tenHangSanXuat;
		this.loaiGiays = loaiGiays;
	}

	@Id
	@Column(name = "id_hang_san_xuat", unique = true, nullable = false)
	public int getIdHangSanXuat() {
		return this.idHangSanXuat;
	}

	public void setIdHangSanXuat(int idHangSanXuat) {
		this.idHangSanXuat = idHangSanXuat;
	}

	@Column(name = "ten_hang_san_xuat", length = 100)
	public String getTenHangSanXuat() {
		return this.tenHangSanXuat;
	}

	public void setTenHangSanXuat(String tenHangSanXuat) {
		this.tenHangSanXuat = tenHangSanXuat;
	}

	@OneToMany(mappedBy = "hangSanXuat")
	@JsonIgnore
	public Set<LoaiGiay> getLoaiGiays() {
		return this.loaiGiays;
	}

	public void setLoaiGiays(Set<LoaiGiay> loaiGiays) {
		this.loaiGiays = loaiGiays;
	}
}
