package com.shoe.entities;
// Generated Nov 27, 2018 12:36:27 AM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TinhTrangDonHang generated by hbm2java
 */
@Entity
@Table(name = "tinh_trang_don_hang", catalog = "quanlygiay")
public class TinhTrangDonHang implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5428886042480347646L;
	private Integer idTinhTrang;
	private String tenTinhTrang;
	private Set<DonHang> donHangs = new HashSet<DonHang>(0);

	public TinhTrangDonHang() {
	}

	public TinhTrangDonHang(String tenTinhTrang, Set<DonHang> donHangs) {
		this.tenTinhTrang = tenTinhTrang;
		this.donHangs = donHangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tinh_trang", unique = true, nullable = false)
	public Integer getIdTinhTrang() {
		return this.idTinhTrang;
	}

	public void setIdTinhTrang(Integer idTinhTrang) {
		this.idTinhTrang = idTinhTrang;
	}

	@Column(name = "ten_tinh_trang", length = 50)
	public String getTenTinhTrang() {
		return this.tenTinhTrang;
	}

	public void setTenTinhTrang(String tenTinhTrang) {
		this.tenTinhTrang = tenTinhTrang;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tinhTrangDonHang")
	public Set<DonHang> getDonHangs() {
		return this.donHangs;
	}

	public void setDonHangs(Set<DonHang> donHangs) {
		this.donHangs = donHangs;
	}

}
